/*
 * Copyright 2026 The 25-ji-code-de Team
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * 打包脚本。零依赖：src/index.js 本身就是可直接发布的 ESM，
 * 这里只额外产出一个 IIFE bundle，给还在用 <script> 标签的 25ji / nightcord。
 */

import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

const source = await readFile(join(root, 'src', 'index.js'), 'utf8');

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

// ESM：原样复制。
await writeFile(join(dist, 'sekai-auth.mjs'), source, 'utf8');

// IIFE：剥掉 export 关键字，把公开符号挂到 window.SekaiAuthSDK 命名空间下。
const EXPORTED = [
  'REFRESH_SKEW_MS',
  'DEFAULT_EXPIRES_IN_S',
  'randomHex',
  'base64UrlEncode',
  'computeCodeChallenge',
  'normalizeProfile',
  'SekaiAuthError',
  'SekaiAuth',
  'createSekaiAuth',
  'SEKAI_PASS_ENDPOINTS',
  'SEKAI_PASS_ISSUER',
];

const body = source
  .replace(/^export default .*$/gm, '')
  // 剥掉 `export`，保留其后的声明（含 `export async function`）
  .replace(/^export (?=(?:async\s+)?(?:function|class|const|let|var)\b)/gm, '');

// 保险：剥完不该再有任何 export/import 残留
for (const leftover of body.matchAll(/^\s*(export|import)\b.*$/gm)) {
  throw new Error(`IIFE bundle still contains a module statement: ${leftover[0].trim()}`);
}

const iife = `${body}
  // --- IIFE bundle footer (generated by scripts/build.mjs) ---
  const SekaiAuthSDK = { ${EXPORTED.join(', ')} };
  global.SekaiAuthSDK = SekaiAuthSDK;
  // 兼容旧的全局名：nightcord 过去用 window.SekaiPassAuth 作为构造器
  global.SekaiPassAuth = SekaiAuth;
})(typeof globalThis !== 'undefined' ? globalThis : self);
`;

await writeFile(
  join(dist, 'sekai-auth.global.js'),
  `(function (global) {\n'use strict';\n${iife}`,
  'utf8',
);

console.log('built dist/sekai-auth.mjs and dist/sekai-auth.global.js');
